from tkinter import *
top=Tk()
top.geometry("1000x800")
top.title("website")
top.config(bg="lightblue")
welcome=Label(top,text="WELCOME TO OUR PAGE",font=('timesnewroman',20,'bold'))
welcome.place(x=365,y=100)
def login():
    kit=Frame(top,bg="skyblue",height=700,width=400)
    kit.pack(fill=X)
    welcome=Label(top,text="LOGIN PAGE",font=('timesnewroman',20,'italic'))
    welcome.place(x=250,y=150)
    box=Entry(top,text="",font=('timesnowroman',15,'italic'),fg="black")
    box.place(x=360,y=300,width=300,height=25)
    box=Entry(top,text="",font=('timesnowroman',15,'italic'),fg="black")
    box.place(x=360,y=300,width=300,height=25)
    box=Entry(top,text="",font=('timesnowroman',15,'italic'),fg="black")
    box.place(x=360,y=400,width=300,height=25)
    button=Button(top,text="LOGIN",font=('timesnewroman',15,'bold'),bg="blue",fg="white",activebackground="yellow",activeforeground="red",command=login)
    button.place(x=400,y=500,height=50,width=100)
    button=Button(top,text="SIGN UP",font=('timesnewroman',15,'bold'),bg="red",fg="white",activebackground="yellow",activeforeground="red",command=login)
    button.place(x=525,y=500,height=50,width=100)
    welcome=Label(top,text="PASSWORD:",font=('timesnewroman',12,'bold'))
    welcome.place(x=250,y=400)
    welcome=Label(top,text="USERNAME:",font=('timesnewroman',12,'bold'))
    welcome.place(x=250,y=300)
    label1=Label(kit,text="Don't have an account",bg="white",fg="blue")
    label1.place(x=460,y=560)


button=Button(top,text="CLICK TO ENTER INTO THE PAGE",font=('timesnewroman',12,'bold'),bg="white",fg="blue",activebackground="yellow",activeforeground="red",command=login)
button.place(x=400,y=500,height=50,width=300)
top.mainloop()

